# Generated by Django 4.2.3 on 2023-08-03 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Med', '0002_remove_orderitem_order_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='total',
        ),
    ]
