# Generated by Django 4.2.3 on 2023-08-03 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Med', '0004_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
